// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroAPI.Database;

#nullable disable

namespace SuperHeroAPI.Migrations
{
    [DbContext(typeof(SuperHeroDbContext))]
    partial class SuperHeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuperHeroAPI.Database.Entities.SuperHero", b =>
                {
                    b.Property<int>("SuperHeroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperHeroID"), 1L, 1);

                    b.Property<short>("Debut")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("SuperHeroID");

                    b.HasIndex("TeamID");

                    b.ToTable("SuperHero");

                    b.HasData(
                        new
                        {
                            SuperHeroID = 1,
                            Debut = (short)1938,
                            FirstName = "Clark",
                            LastName = "Kent",
                            Name = "Superman",
                            Place = "Metropolis",
                            TeamID = 1
                        },
                        new
                        {
                            SuperHeroID = 2,
                            Debut = (short)1963,
                            FirstName = "Tony",
                            LastName = "Stark",
                            Name = "Iron Man",
                            Place = "Malibu",
                            TeamID = 2
                        });
                });

            modelBuilder.Entity("SuperHeroAPI.Database.Entities.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"), 1L, 1);

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("TeamID");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            TeamName = "Justice League"
                        },
                        new
                        {
                            TeamID = 2,
                            TeamName = "Avengers"
                        });
                });

            modelBuilder.Entity("SuperHeroAPI.Database.Entities.SuperHero", b =>
                {
                    b.HasOne("SuperHeroAPI.Database.Entities.Team", "Team")
                        .WithMany("SuperHeroes")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SuperHeroAPI.Database.Entities.Team", b =>
                {
                    b.Navigation("SuperHeroes");
                });
#pragma warning restore 612, 618
        }
    }
}
